version: '3'
volumes:
  mariadb_data:
networks:
  moodle-network:
    driver: bridge
services:
  web:
    image: edissonsigua/moodle-web
    container_name: moodle-web
    restart: unless-stopped
    bind:
      context: nginx
      dockerfile: ./nginx.Dockerfile
    depends_on:
    - db
    networks:
      - moodle-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/moodle.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/php-fpm.conf:/etc/nginx/conf.d/php-fpm.conf:ro
      - ./php-fpm/phpsocket:/run/php-fpm:rw
      - ./moodle:/var/www/moodle:rw
      - ./moodledata:/var/www/moodledata:rw
    ports:
      - "80:80"
  php:
    image: edissonsigua/moodle-php
    container_name: moodle-php
    restart: unless-stopped
    depends_on:
    - db
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - moodle-network
    volumes:
      - ./php-fpm/phpsocket:/run/php-fpm:rw
      - ./moodle:/var/www/moodle:rw
      - ./moodledata:/var/www/moodledata:rw
  cron:
    image: edissonsigua/moodle-cron
    container_name: moodle-cron
    restart: unless-stopped
    depends_on:
    - db
    networks:
      - moodle-network
    volumes:
      - ./moodle:/var/www/moodle:rw
      - ./moodledata:/var/www/moodledata:rw
  db:
    image: mariadb
    container_name: moodle-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      #- ./moodledb:/var/lib/mysql # if you want to use a bind folder
    networks:
      - moodle-network
    ports:
      - "3306:3306"
  cache:
    image: redis
    container_name: moodle-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - ./redis:/data
    networks:
      - moodle-network
